language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - coverage=yes
  matrix:
    - setup=basic
    - setup=stable
    - setup=lowest

before_install:
  - composer config discard-changes true

before_script:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $coverage = 'yes' ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
